import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://lab-02622-bos.lab-internal.pega.com/prweb/app/default/_56mEsR4RqBouCrZGfkkFF8v406BUOZt*/!STANDARD');
  await page.getByPlaceholder('User name').click();
  await page.getByPlaceholder('User name').fill('cacsrcti1');
  await page.getByPlaceholder('User name').press('Tab');
  await page.getByPlaceholder('Password', { exact: true }).fill('install123!');
  await page.getByPlaceholder('Password', { exact: true }).press('Enter');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.goto('https://lab-02622-bos.lab-internal.pega.com/prweb/app/PegaCallConstellationSample');
  await page.getByLabel('Phone panel').click();
  await page.getByLabel('CTI Link').selectOption('12');
  await page.getByLabel('Extension').click();
  await page.getByLabel('Extension').fill('2963');
  await page.getByLabel('Extension').press('Tab');
  await page.getByLabel('Agent ID').fill('2463');
  await page.getByLabel('Agent ID').press('Tab');
  await page.getByLabel('Password').fill('2963');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('[id="_dbdqzlcte-combobox"]').getByLabel('Open combobox list').click();
  await page.getByText('•Ready').click();
  await page.getByText(':07').click();
  await page.goto('https://lab-02622-bos.lab-internal.pega.com/prweb/app/PegaCallConstellationSample/interactions/I-161002');
  await page.getByLabel('Collapse call control panel').click();
  await page.getByTestId('Search by:select:control').selectOption('Consumer');
  await page.getByTestId('Phone number:input:control').selectOption('Consumer');
  await page.getByTestId('First name:input:control').click();
  await page.getByTestId('First name:input:control').fill('s');
  await page.locator('header').filter({ hasText: '2963' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByTestId('search').click();
  await page.getByRole('row', { name: 'Smith Smith Steve steveRsmith@sample.com +914041974520 *****6789 Wellesley MA Matthew Smith', exact: true }).getByTestId(':form-field:label').locator('div').click();
  await page.getByLabel('Interaction').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('div').filter({ hasText: /^Submit$/ }).dblclick();
  await page.locator('fieldset[name="caseInfo\\.content\\.QuestionSets\\[0\\]\\.czQuestions\\[0\\]\\.czQuestionOutcome"] label').filter({ hasText: 'Pass' }).locator('div').click();
  await page.locator('fieldset[name="caseInfo\\.content\\.QuestionSets\\[0\\]\\.czQuestions\\[0\\]\\.czQuestionOutcome"] label').filter({ hasText: 'Pass' }).locator('div').click();
  await page.locator('[id="_af3civxom-field"] label').filter({ hasText: 'Pass' }).locator('div').click();
  await page.locator('fieldset[name="caseInfo\\.content\\.QuestionSets\\[0\\]\\.czQuestions\\[0\\]\\.czQuestionOutcome"]').getByText('Pass').click();
  await page.locator('[id="_af3civxom-field"]').getByText('Pass').click();
  await page.locator('[id="_dlvhb85le-field"]').getByTestId(':form-field:label').click();
  await page.locator('[id="_hzvkr7mdm-field"]').getByText('Pass').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('row', { name: 'Quad Play Plus - 0001 Quad' }).getByTestId(':form-field:label').locator('div').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByLabel('Expand call control panel').click();
  await page.getByTestId(':summary-item:actions').getByTestId(':menu-button:').click();
  await page.getByText('Transfer').click();
  await page.getByText('Call and interaction').click();
  await page.getByLabel('Interaction').click();
  await page.getByTestId(':menu-item:').getByTestId(':summary-item:primary').click();
  await page.getByLabel('Reason').click();
  await page.getByText('On break').click();
  await page.getByTestId(':text-area:control').click();
  await page.getByTestId(':text-area:control').fill('Transfer call plus interaction');
  await page.getByLabel('Dial pad').click();
  await page.getByTestId(':form:').getByTestId(':input:control').click();
  await page.getByTestId(':form:').getByTestId(':input:control').fill('2983');
  await page.locator('div').filter({ hasText: 'InteractionArrow down to open' }).nth(1).click();
  await page.locator('header').filter({ hasText: 'Transfer call and interaction' }).click();
  await page.getByTestId(':form:').getByTestId(':input:control').click();
  await page.getByTestId(':form:').getByTestId(':input:control').fill('2983');
  await page.getByTestId(':form:').getByTestId(':input:control').press('Tab');
  await page.locator('div').filter({ hasText: /^12ABC3DEF4GHI5JKL6MNO7PQRS8TUV9WXYZ\*0\+#$/ }).nth(1).click();
  await page.locator('body').press('Tab');
  await page.getByLabel('Close').press('Tab');
  await page.getByLabel('Interaction').press('Shift+Tab');
  await page.getByLabel('Close').press('Shift+Tab');
  await page.getByRole('button', { name: 'Transfer' }).press('Enter');
  await page.getByLabel('Close').click();
  await page.getByTestId(':summary-item:actions').getByTestId(':menu-button:').click();
  await page.getByLabel('Hang up').getByTestId(':summary-item:primary').click();
  await page.getByTestId(':combo-box:control').click();
  await page.getByText('Break-Cofee').click();
  await page.getByTestId(':combo-box:control').click();
  await page.getByText('Logout').click();
  await page.getByText('Dismiss case').click();
});